module.exports = {
  projects: [
    '<rootDir>/apps/coljobs',
    '<rootDir>/libs/shared/ui/forms',
    '<rootDir>/libs/shared/data-access/firebase',
    '<rootDir>/libs/shared/environments',
    '<rootDir>/libs/shared/util/sdk',
    '<rootDir>/libs/web/shell/feature',
    '<rootDir>/libs/web/layout',
    '<rootDir>/libs/web/ui/table',
    '<rootDir>/libs/company/data-access',
    '<rootDir>/libs/company/feature-list',
    '<rootDir>/libs/job-post/data-access',
    '<rootDir>/libs/job-post/feature-list',
    '<rootDir>/libs/shared/config-transloco',
    '<rootDir>/libs/auth/data-access',
    '<rootDir>/libs/auth/feature',
    '<rootDir>/libs/auth/ui',
    '<rootDir>/libs/shared/assets',
  ],
};
